"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Api = exports.txClient = exports.registry = void 0;
const proto_signing_1 = require("@cosmjs/proto-signing");
const rest_1 = require("./rest");
Object.defineProperty(exports, "Api", { enumerable: true, get: function () { return rest_1.Api; } });
const types = [];
exports.registry = new proto_signing_1.Registry(types);
const txClient = {};
exports.txClient = txClient;
