/**
 * This file was automatically generated by cosmwasm-typescript-gen@0.3.6.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the cosmwasm-typescript-gen generate command to regenerate this file.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
export class FinQueryClient {
    constructor(client, contractAddress) {
        this.config = () => __awaiter(this, void 0, void 0, function* () {
            return this.client.queryContractSmart(this.contractAddress, {
                config: {},
            });
        });
        this.simulation = ({ offerAsset, }) => __awaiter(this, void 0, void 0, function* () {
            return this.client.queryContractSmart(this.contractAddress, {
                simulation: {
                    offer_asset: offerAsset,
                },
            });
        });
        this.order = ({ orderIdx, }) => __awaiter(this, void 0, void 0, function* () {
            return this.client.queryContractSmart(this.contractAddress, {
                order: {
                    order_idx: orderIdx,
                },
            });
        });
        this.ordersByUser = ({ address, limit, startAfter, }) => __awaiter(this, void 0, void 0, function* () {
            return this.client.queryContractSmart(this.contractAddress, {
                orders_by_user: {
                    address,
                    limit,
                    start_after: startAfter,
                },
            });
        });
        this.price = ({ price }) => __awaiter(this, void 0, void 0, function* () {
            return this.client.queryContractSmart(this.contractAddress, {
                price: {
                    price,
                },
            });
        });
        this.book = ({ limit, offset, }) => __awaiter(this, void 0, void 0, function* () {
            return this.client.queryContractSmart(this.contractAddress, {
                book: {
                    limit,
                    offset,
                },
            });
        });
        this.client = client;
        this.contractAddress = contractAddress;
        this.config = this.config.bind(this);
        this.simulation = this.simulation.bind(this);
        this.order = this.order.bind(this);
        this.ordersByUser = this.ordersByUser.bind(this);
        this.price = this.price.bind(this);
        this.book = this.book.bind(this);
    }
}
export class FinClient extends FinQueryClient {
    constructor(client, sender, contractAddress) {
        super(client, contractAddress);
        this.receive = ({ amount, msg, sender, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                receive: {
                    amount,
                    msg,
                    sender,
                },
            }, fee, memo, funds);
        });
        this.launch = (fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                launch: {},
            }, fee, memo, funds);
        });
        this.updateConfig = ({ owner, pricePrecision, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                update_config: {
                    owner,
                    price_precision: pricePrecision,
                },
            }, fee, memo, funds);
        });
        this.submitOrder = ({ price, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                submit_order: {
                    price,
                },
            }, fee, memo, funds);
        });
        this.swap = ({ beliefPrice, maxSpread, offerAsset, to, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                swap: {
                    belief_price: beliefPrice,
                    max_spread: maxSpread,
                    offer_asset: offerAsset,
                    to,
                },
            }, fee, memo, funds);
        });
        this.retractOrder = ({ amount, orderIdx, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                retract_order: {
                    amount,
                    order_idx: orderIdx,
                },
            }, fee, memo, funds);
        });
        this.retractOrders = ({ orderIdxs, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                retract_orders: {
                    order_idxs: orderIdxs,
                },
            }, fee, memo, funds);
        });
        this.withdrawOrders = ({ orderIdxs, }, fee = "auto", memo, funds) => __awaiter(this, void 0, void 0, function* () {
            return yield this.client.execute(this.sender, this.contractAddress, {
                withdraw_orders: {
                    order_idxs: orderIdxs,
                },
            }, fee, memo, funds);
        });
        this.client = client;
        this.sender = sender;
        this.contractAddress = contractAddress;
        this.receive = this.receive.bind(this);
        this.launch = this.launch.bind(this);
        this.updateConfig = this.updateConfig.bind(this);
        this.submitOrder = this.submitOrder.bind(this);
        this.swap = this.swap.bind(this);
        this.retractOrder = this.retractOrder.bind(this);
        this.retractOrders = this.retractOrders.bind(this);
        this.withdrawOrders = this.withdrawOrders.bind(this);
    }
}
