import { Writer, Reader } from "protobufjs/minimal";
import { DeepPartial } from "../../../../../../../types";
export declare const protobufPackage = "ethermint.evm.v1";
/** Params defines the EVM module parameters */
export interface Params {
    /**
     * evm denom represents the token denomination used to run the EVM state
     * transitions.
     */
    evm_denom: string;
    /** enable create toggles state transitions that use the vm.Create function */
    enable_create: boolean;
    /** enable call toggles state transitions that use the vm.Call function */
    enable_call: boolean;
    /** extra eips defines the additional EIPs for the vm.Config */
    extra_eips: number[];
    /** chain config defines the EVM chain configuration parameters */
    chain_config: ChainConfig | undefined;
    /**
     * Allow unprotected transactions defines if replay-protected (i.e non EIP155
     * signed) transactions can be executed on the state machine.
     */
    allow_unprotected_txs: boolean;
}
/**
 * ChainConfig defines the Ethereum ChainConfig parameters using *sdk.Int values
 * instead of *big.Int.
 */
export interface ChainConfig {
    /** Homestead switch block (nil no fork, 0 = already homestead) */
    homestead_block: string;
    /** TheDAO hard-fork switch block (nil no fork) */
    dao_fork_block: string;
    /** Whether the nodes supports or opposes the DAO hard-fork */
    dao_fork_support: boolean;
    /**
     * EIP150 implements the Gas price changes
     * (https://github.com/ethereum/EIPs/issues/150) EIP150 HF block (nil no fork)
     */
    eip150_block: string;
    /** EIP150 HF hash (needed for header only clients as only gas pricing changed) */
    eip150_hash: string;
    /** EIP155Block HF block */
    eip155_block: string;
    /** EIP158 HF block */
    eip158_block: string;
    /** Byzantium switch block (nil no fork, 0 = already on byzantium) */
    byzantium_block: string;
    /** Constantinople switch block (nil no fork, 0 = already activated) */
    constantinople_block: string;
    /** Petersburg switch block (nil same as Constantinople) */
    petersburg_block: string;
    /** Istanbul switch block (nil no fork, 0 = already on istanbul) */
    istanbul_block: string;
    /** Eip-2384 (bomb delay) switch block (nil no fork, 0 = already activated) */
    muir_glacier_block: string;
    /** Berlin switch block (nil = no fork, 0 = already on berlin) */
    berlin_block: string;
    /** London switch block (nil = no fork, 0 = already on london) */
    london_block: string;
    /** Eip-4345 (bomb delay) switch block (nil = no fork, 0 = already activated) */
    arrow_glacier_block: string;
    /** EIP-5133 (bomb delay) switch block (nil = no fork, 0 = already activated) */
    gray_glacier_block: string;
    /** Virtual fork after The Merge to use as a network splitter */
    merge_netsplit_block: string;
}
/** State represents a single Storage key value pair item. */
export interface State {
    key: string;
    value: string;
}
/**
 * TransactionLogs define the logs generated from a transaction execution
 * with a given hash. It it used for import/export data as transactions are not
 * persisted on blockchain state after an upgrade.
 */
export interface TransactionLogs {
    hash: string;
    logs: Log[];
}
/**
 * Log represents an protobuf compatible Ethereum Log that defines a contract
 * log event. These events are generated by the LOG opcode and stored/indexed by
 * the node.
 */
export interface Log {
    /** address of the contract that generated the event */
    address: string;
    /** list of topics provided by the contract. */
    topics: string[];
    /** supplied by the contract, usually ABI-encoded */
    data: Uint8Array;
    /** block in which the transaction was included */
    block_number: number;
    /** hash of the transaction */
    tx_hash: string;
    /** index of the transaction in the block */
    tx_index: number;
    /** hash of the block in which the transaction was included */
    block_hash: string;
    /** index of the log in the block */
    index: number;
    /**
     * The Removed field is true if this log was reverted due to a chain
     * reorganisation. You must pay attention to this field if you receive logs
     * through a filter query.
     */
    removed: boolean;
}
/** TxResult stores results of Tx execution. */
export interface TxResult {
    /**
     * contract_address contains the ethereum address of the created contract (if
     * any). If the state transition is an evm.Call, the contract address will be
     * empty.
     */
    contract_address: string;
    /** bloom represents the bloom filter bytes */
    bloom: Uint8Array;
    /**
     * tx_logs contains the transaction hash and the proto-compatible ethereum
     * logs.
     */
    tx_logs: TransactionLogs | undefined;
    /** ret defines the bytes from the execution. */
    ret: Uint8Array;
    /** reverted flag is set to true when the call has been reverted */
    reverted: boolean;
    /** gas_used notes the amount of gas consumed while execution */
    gas_used: number;
}
/** AccessTuple is the element type of an access list. */
export interface AccessTuple {
    /** hex formatted ethereum address */
    address: string;
    /** hex formatted hashes of the storage keys */
    storage_keys: string[];
}
/** TraceConfig holds extra parameters to trace functions. */
export interface TraceConfig {
    /** custom javascript tracer */
    tracer: string;
    /**
     * overrides the default timeout of 5 seconds for JavaScript-based tracing
     * calls
     */
    timeout: string;
    /** number of blocks the tracer is willing to go back */
    reexec: number;
    /** disable stack capture */
    disable_stack: boolean;
    /** disable storage capture */
    disable_storage: boolean;
    /** print output during capture end */
    debug: boolean;
    /** maximum length of output, but zero means unlimited */
    limit: number;
    /** Chain overrides, can be used to execute a trace using future fork rules */
    overrides: ChainConfig | undefined;
    /** enable memory capture */
    enable_memory: boolean;
    /** enable return data capture */
    enable_return_data: boolean;
}
export declare const Params: {
    encode(message: Params, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): Params;
    fromJSON(object: any): Params;
    toJSON(message: Params): unknown;
    fromPartial(object: DeepPartial<Params>): Params;
};
export declare const ChainConfig: {
    encode(message: ChainConfig, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): ChainConfig;
    fromJSON(object: any): ChainConfig;
    toJSON(message: ChainConfig): unknown;
    fromPartial(object: DeepPartial<ChainConfig>): ChainConfig;
};
export declare const State: {
    encode(message: State, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): State;
    fromJSON(object: any): State;
    toJSON(message: State): unknown;
    fromPartial(object: DeepPartial<State>): State;
};
export declare const TransactionLogs: {
    encode(message: TransactionLogs, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): TransactionLogs;
    fromJSON(object: any): TransactionLogs;
    toJSON(message: TransactionLogs): unknown;
    fromPartial(object: DeepPartial<TransactionLogs>): TransactionLogs;
};
export declare const Log: {
    encode(message: Log, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): Log;
    fromJSON(object: any): Log;
    toJSON(message: Log): unknown;
    fromPartial(object: DeepPartial<Log>): Log;
};
export declare const TxResult: {
    encode(message: TxResult, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): TxResult;
    fromJSON(object: any): TxResult;
    toJSON(message: TxResult): unknown;
    fromPartial(object: DeepPartial<TxResult>): TxResult;
};
export declare const AccessTuple: {
    encode(message: AccessTuple, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): AccessTuple;
    fromJSON(object: any): AccessTuple;
    toJSON(message: AccessTuple): unknown;
    fromPartial(object: DeepPartial<AccessTuple>): AccessTuple;
};
export declare const TraceConfig: {
    encode(message: TraceConfig, writer?: Writer): Writer;
    decode(input: Reader | Uint8Array, length?: number): TraceConfig;
    fromJSON(object: any): TraceConfig;
    toJSON(message: TraceConfig): unknown;
    fromPartial(object: DeepPartial<TraceConfig>): TraceConfig;
};
