import { EncodeObject, Registry } from "@cosmjs/proto-signing";
import { MsgBatchSendToEthClaim, MsgBatchSendToEthClaimResponse, MsgCancelSendToEth, MsgCancelSendToEthResponse, MsgConfirmBatch, MsgConfirmBatchResponse, MsgConfirmLogicCall, MsgConfirmLogicCallResponse, MsgERC20DeployedClaim, MsgERC20DeployedClaimResponse, MsgExecuteIbcAutoForwards, MsgExecuteIbcAutoForwardsResponse, MsgLogicCallExecutedClaim, MsgLogicCallExecutedClaimResponse, MsgRequestBatch, MsgRequestBatchResponse, MsgSendToCosmosClaim, MsgSendToCosmosClaimResponse, MsgSendToEth, MsgSendToEthResponse, MsgSetOrchestratorAddress, MsgSetOrchestratorAddressResponse, MsgSubmitBadSignatureEvidence, MsgSubmitBadSignatureEvidenceResponse, MsgValsetConfirm, MsgValsetConfirmResponse, MsgValsetUpdatedClaim, MsgValsetUpdatedClaimResponse } from "./msgs";
import { GravityExtension, setupGravityExtension } from "./queries";
export { EventOutgoingBatch, EventOutgoingBatchCanceled, OutgoingLogicCall, OutgoingTransferTx, OutgoingTxBatch, } from "./batch";
export { GenesisState, GravityNonces, Params } from "./genesis";
export { Query, QueryAttestationsRequest, QueryAttestationsResponse, QueryBatchConfirmsRequest, QueryBatchConfirmsResponse, QueryBatchFeeRequest, QueryBatchFeeResponse, QueryBatchRequestByNonceRequest, QueryBatchRequestByNonceResponse, QueryCurrentValsetRequest, QueryCurrentValsetResponse, QueryDelegateKeysByEthAddress, QueryDelegateKeysByEthAddressResponse, QueryDelegateKeysByOrchestratorAddress, QueryDelegateKeysByOrchestratorAddressResponse, QueryDelegateKeysByValidatorAddress, QueryDelegateKeysByValidatorAddressResponse, QueryDenomToERC20Request, QueryDenomToERC20Response, QueryERC20ToDenomRequest, QueryERC20ToDenomResponse, QueryLastEventNonceByAddrRequest, QueryLastEventNonceByAddrResponse, QueryLastObservedEthBlockRequest, QueryLastObservedEthBlockResponse, QueryLastObservedEthNonceRequest, QueryLastObservedEthNonceResponse, QueryLastPendingBatchRequestByAddrRequest, QueryLastPendingBatchRequestByAddrResponse, QueryLastPendingLogicCallByAddrRequest, QueryLastPendingLogicCallByAddrResponse, QueryLastPendingValsetRequestByAddrRequest, QueryLastPendingValsetRequestByAddrResponse, QueryLastValsetRequestsRequest, QueryLastValsetRequestsResponse, QueryLogicConfirmsRequest, QueryLogicConfirmsResponse, QueryOutgoingLogicCallsRequest, QueryOutgoingLogicCallsResponse, QueryOutgoingTxBatchesRequest, QueryOutgoingTxBatchesResponse, QueryParamsRequest, QueryParamsResponse, QueryPendingIbcAutoForwards, QueryPendingIbcAutoForwardsResponse, QueryPendingSendToEth, QueryPendingSendToEthResponse, QueryValsetConfirmRequest, QueryValsetConfirmResponse, QueryValsetConfirmsByNonceRequest, QueryValsetConfirmsByNonceResponse, QueryValsetRequestRequest, QueryValsetRequestResponse, } from "./query";
declare const types: (string | {
    encode(_: MsgBatchSendToEthClaimResponse, writer?: import("cosmjs-types/binary").BinaryWriter): import("cosmjs-types/binary").BinaryWriter;
    decode(input: import("cosmjs-types/binary").BinaryReader | Uint8Array, length?: number | undefined): MsgBatchSendToEthClaimResponse;
    fromJSON(_: any): MsgBatchSendToEthClaimResponse;
    toJSON(_: MsgBatchSendToEthClaimResponse): unknown;
    fromPartial(_: Partial<MsgBatchSendToEthClaimResponse>): MsgBatchSendToEthClaimResponse;
})[][];
export declare const registry: Registry;
declare const msg: {
    msgBatchSendToEthClaim: (data: MsgBatchSendToEthClaim) => EncodeObject;
    msgBatchSendToEthClaimResponse: (data: MsgBatchSendToEthClaimResponse) => EncodeObject;
    msgCancelSendToEth: (data: MsgCancelSendToEth) => EncodeObject;
    msgCancelSendToEthResponse: (data: MsgCancelSendToEthResponse) => EncodeObject;
    msgConfirmBatch: (data: MsgConfirmBatch) => EncodeObject;
    msgConfirmBatchResponse: (data: MsgConfirmBatchResponse) => EncodeObject;
    msgConfirmLogicCall: (data: MsgConfirmLogicCall) => EncodeObject;
    msgConfirmLogicCallResponse: (data: MsgConfirmLogicCallResponse) => EncodeObject;
    msgERC20DeployedClaim: (data: MsgERC20DeployedClaim) => EncodeObject;
    msgERC20DeployedClaimResponse: (data: MsgERC20DeployedClaimResponse) => EncodeObject;
    msgExecuteIbcAutoForwards: (data: MsgExecuteIbcAutoForwards) => EncodeObject;
    msgExecuteIbcAutoForwardsResponse: (data: MsgExecuteIbcAutoForwardsResponse) => EncodeObject;
    msgLogicCallExecutedClaim: (data: MsgLogicCallExecutedClaim) => EncodeObject;
    msgLogicCallExecutedClaimResponse: (data: MsgLogicCallExecutedClaimResponse) => EncodeObject;
    msgRequestBatch: (data: MsgRequestBatch) => EncodeObject;
    msgRequestBatchResponse: (data: MsgRequestBatchResponse) => EncodeObject;
    msgSendToCosmosClaim: (data: MsgSendToCosmosClaim) => EncodeObject;
    msgSendToCosmosClaimResponse: (data: MsgSendToCosmosClaimResponse) => EncodeObject;
    msgSendToEth: (data: MsgSendToEth) => EncodeObject;
    msgSendToEthResponse: (data: MsgSendToEthResponse) => EncodeObject;
    msgSetOrchestratorAddress: (data: MsgSetOrchestratorAddress) => EncodeObject;
    msgSetOrchestratorAddressResponse: (data: MsgSetOrchestratorAddressResponse) => EncodeObject;
    msgSubmitBadSignatureEvidence: (data: MsgSubmitBadSignatureEvidence) => EncodeObject;
    msgSubmitBadSignatureEvidenceResponse: (data: MsgSubmitBadSignatureEvidenceResponse) => EncodeObject;
    msgValsetConfirm: (data: MsgValsetConfirm) => EncodeObject;
    msgValsetConfirmResponse: (data: MsgValsetConfirmResponse) => EncodeObject;
    msgValsetUpdatedClaim: (data: MsgValsetUpdatedClaim) => EncodeObject;
    msgValsetUpdatedClaimResponse: (data: MsgValsetUpdatedClaimResponse) => EncodeObject;
};
export { GravityExtension, msg, setupGravityExtension, types };
